project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
